name: Production Infra Setup in Terraform

trigger:
 branches:
   include:
     - master

pool: 
 name: satishpool
 demands:
  - agent.name -equals ranjanofficeagent

parameters:
  - name: environment
    default: dev
    type: string
    values:
      - dev
      - prod 

stages:
# Terraform Installation and Initialization for Dev Environment
  - stage: terraforminstallandinitfordev
    displayName: Terraform Installation and Initialization for Dev Environment
    jobs:
      - job: terraforminstalldev
        displayName: Terraform Install for Dev
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
      - job: terraforminitdev
        displayName: Terraform Initialization for Dev
        dependsOn: terraforminstalldev
        steps:
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
              backendServiceArm: 'satishranjanwindowshost'
              backendAzureRmResourceGroupName: 'satishrg'
              backendAzureRmStorageAccountName: 'satishranstorage'
              backendAzureRmContainerName: 'satishcontainer'
              backendAzureRmKey: 'terraform.tfstate'

  # Terraform Installation and Initialization for Prod Environment
  - stage: terraforminstallandinitforprod
    displayName: Terraform Installation and Initialization for Prod Environment
    jobs:
      - job: terraforminstallprod
        displayName: Terraform Install for Prod
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
      - job: terraforminitprod
        displayName: Terraform Initialization for Prod
        dependsOn: terraforminstallprod
        steps:
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environment/prod'
              backendServiceArm: 'satishranjanwindowshost'
              backendAzureRmResourceGroupName: 'satishrg'
              backendAzureRmStorageAccountName: 'satishranstorage'
              backendAzureRmContainerName: 'satishcontainer'
              backendAzureRmKey: 'terraform.tfstate'
  - stage: tfplanforprod
    dependsOn: terraforminstallandinitforprod
    displayName: Terraform Plan
    jobs:
     - job: terraformplan
       displayName: Terraform plan
       steps:
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environment/prod'
              backendServiceArm: 'satishranjanwindowshost'
              backendAzureRmResourceGroupName: 'satishrg'
              backendAzureRmStorageAccountName: 'satishranstorage'
              backendAzureRmContainerName: 'satishcontainer'
              backendAzureRmKey: 'terraform.tfstate'

          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environment/prod'
              environmentServiceNameAzureRM: 'satishranjanwindowshost'
  - stage: ManualApproval
    displayName: Manual Approval Needed
    jobs: 
    - job: ManualApprovalJob
      displayName: Manual Approval Job
      pool: server
      steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'satish.ranjan7183@gmail.com'
          instructions: 'Please validate the plan and continue'

  # - stage: terraforminstallationandinitforprod
  #   displayName: Terraform Installation and Initialization
  #   jobs:
  #     - job: terraforminstallation
  #       displayName: Terraform Installation
  #       steps:
  #        - task: TerraformInstaller@1
  #          inputs:
  #            terraformVersion: 'latest'
  #     - job: terraforminit
  #       displayName: Terraform Init
  #       steps:
  #         - task: TerraformTaskV4@4
  #           inputs:
  #             provider: 'azurerm'
  #             command: 'init'
  #             workingDirectory: '$(workdir)'
  #             backendServiceArm: 'satishranjanwindowshost'
  #             backendAzureRmResourceGroupName: 'satishrg'
  #             backendAzureRmStorageAccountName: 'satishranstorage'
  #             backendAzureRmContainerName: 'satishcontainer'
  #             backendAzureRmKey: 'terraform.tfstate'
  # - stage: terraformplanfordev
  #   dependsOn: terraforminstallationandinitfordev
  #   displayName: Terraform Plan
  #   jobs:
  #    - job: terraformplan
  #      displayName: Terraform plan
  #      steps:
  #         - task: TerraformTaskV4@4
  #           inputs:
  #             provider: 'azurerm'
  #             command: 'init'
  #             workingDirectory: '$(workdir)'
  #             backendServiceArm: 'satishranjanwindowshost'
  #             backendAzureRmResourceGroupName: 'satishrg'
  #             backendAzureRmStorageAccountName: 'satishranstorage'
  #             backendAzureRmContainerName: 'satishcontainer'
  #             backendAzureRmKey: 'terraform.tfstate'

  #         - task: TerraformTaskV4@4
  #           inputs:
  #             provider: 'azurerm'
  #             command: 'plan'
  #             workingDirectory: '$(workdir)'
  #             environmentServiceNameAzureRM: 'satishranjanwindowshost'              